# Generated by Django 3.2.3 on 2021-05-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.CharField(choices=[('uplex', 'UPLEX'), ('mju', 'MJU'), ('not-specified', 'Not Specified')], max_length=100, null=True),
        ),
    ]
