# Generated by Django 3.2.3 on 2021-05-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zonecode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.CharField(choices=[('mju', 'MJU'), ('not-specified', 'Not Specified'), ('uplex', 'UPLEX')], max_length=100, null=True),
        ),
    ]
